### PR TITLE
Completed: Use enum for operators

### PR DESCRIPTION
**Pull request by lexidor**
Addresses #8

### CODE REVIEW

**Comment by lexidor** [comment]
The HHVM4.0.4 typechecker does not agree with the HHVM4.15 typechecker. This will be great!

**Comment by lexidor** [comment]
This hurts real bad. HHVM 4.15 allows switches with incompatible types. The only thing I can really do is sprinkle in some `as Operator` after the switch argument until it builds. This will change the behavior is the Operator isn't really an Operator.

**Comment by lexidor** [comment]
I opened an issue for that, but that doesn't help me now... :cry: https://github.com/facebook/hhvm/issues/8544

**Comment by lexidor** [comment]
### Changelog
 
 - The Operator enum contains all supported and some non-supported SQL operators.
 - Comparisons against operator which were previously string have been replaced with their enum members where obvious from context.
 - Switches use their enum member counterpart.
 - Empty string is nolonger used as a <no operator here> value. Null will be used instead.

### Notes
 - I don't have a project that I can spin up to do through testing.
 - I grepped for `/=?['"]['"]/` to check for assignments and comparisons for the <no opertor here> value.
 - I made sure to cast using `as nonnull` instead of `as Operator` where possible. This will allow the same non-operator typed string to flow through the code like they used to.

Pretty please, don't merge this blindly. There is a chance I broke something without knowing it (most likely in untyped or stringly typed code). If you can compare this to the master version on some project, that would be amazing.

**Comment by ssandler** [comment]
@lexidor thank you so much for this PR! As you mentioned, I took a careful look and pulled this into our full repo to run the entire test suite that depends on hack-sql-fake, everything is looking good.

There's a small conflict with the newly handled Ampersand operator, and we've added a CLA to this repo. Would you mind rebasing to resolve those two issues? I'll be happy to merge this afterward!

**Comment by lexidor** [comment]
@ssandler I am back from Germany. Thanks for running this branch against your more expansive test suite. CLI signed and merge conflict resolved.

**Pull request merged**
